version: '3'
services:
  web:
    build: .
    ports:
      - "4000:4000"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080